//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class notesgroups
    {
        public int NotesgroupsId { get; set; }
        public int NoteId { get; set; }
        public int GroupId { get; set; }
        public int UserId { get; set; }
    
        public virtual group group { get; set; }
        public virtual note note { get; set; }
    }
}
