//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class types
    {
        public types()
        {
            this.note = new HashSet<note>();
        }
    
        public int TypeId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual ICollection<note> note { get; set; }
    }
}
