//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class userfriendsinvites
    {
        public int UserfriendsinviteId { get; set; }
        public string State { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
