//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class locations
    {
        public locations()
        {
            this.notes = new HashSet<notes>();
        }
    
        public int LocationId { get; set; }
        public Nullable<decimal> XCord { get; set; }
        public Nullable<decimal> YCord { get; set; }
        public Nullable<decimal> ZCord { get; set; }
    
        public virtual ICollection<notes> notes { get; set; }
    }
}
